version: '2'
services:
  fpm:
    image: php:8.3.0alpha2-fpm-alpine
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:stable-alpine3.17-slim
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/app.vhost:/etc/nginx/conf.d/app.vhost
    ports:
      - "80:80"
    links:
      - fpm